name: cabwire
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  get: ^4.6.6
  get_it: ^8.0.2
  intl: ^0.20.2
  talker_logger: ^4.4.1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  path: ^1.9.0
  share_plus: ^10.1.2
  http: ^1.3.0
  logger: ^2.5.0
  isolates_helper: ^0.5.2
  hive: ^2.2.3
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.2
  firebase_crashlytics: ^4.3.2
  firebase_analytics: ^11.4.2
  package_info_plus: ^8.1.3
  device_info_plus: ^11.3.3
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.2.1
  synchronized: ^3.3.1
  app_settings: ^6.1.1
  flutter_local_notifications: ^19.0.0
  flutter_native_splash: ^2.4.5
  google_maps_flutter: ^2.12.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  mime: ^2.0.0
  socket_io_client: ^3.1.2
  jwt_decoder: ^2.0.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  flutter_polyline_points: ^2.1.0
  geocoding: ^2.1.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.24.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - .env

  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
